spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8082/
          predicates:
            - Path=/produits/**
        - id: r2
          uri: http://localhost:8081/commandes
          predicates:
            - Path=/commandes/**
  application:
    name: gateway-service
server:
  port: 8888